version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_DB: trivago
      POSTGRES_USER: trivago
      POSTGRES_PASSWORD: changeit
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - "9090:8080"
    profiles:
      - debug